# Generated by Django 3.2 on 2021-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
