# Generated by Django 3.2 on 2021-09-02 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_alter_chats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='spoke_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spoke', to=settings.AUTH_USER_MODEL),
        ),
    ]
