# Generated by Django 3.2 on 2021-09-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_chats_spoke_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='spoke_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
