# Generated by Django 3.2 on 2021-09-05 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0005_alter_chats_spoke_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='spoke_by',
            new_name='spokeBy',
        ),
        migrations.AddField(
            model_name='chats',
            name='currentUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
